apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: kaniko-build-wt
spec:
  templates:
    - name: kaniko-clone-build-template
      inputs:
        artifacts:
          - name: source
            path: /workspace
            git:
              repo: "git@github.com:roldyxoriginal/RIS-VERSION_1.git"
              sshPrivateKeySecret:
                  name: github-creds
                  key: ssh-private-key
              insecureIgnoreHostKey: true
      container:
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
          capabilities:
            add: [CHOWN, FOWNER, SETUID, SETGID, DAC_OVERRIDE]
        image: gcr.io/kaniko-project/executor:v1.6.0
        #env:
        command: ["/kaniko/executor"]
        args:
          [
            "--context=dir:///workspace/",
            "--dockerfile=/workspace/Dockerfile",
            "--destination=harbor.itsos.ar/dummy/http:latest",
            "--cache=true",
            "--use-new-run"
          ]
        volumeMounts:
        - name: auth-config
          mountPath: /kaniko/.docker/
      volumes:
        - name: auth-config
          projected:
            sources:
              - secret:
                  name: regcred
                  items:
                    - key: .dockerconfigjson
                      path: config.json