apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: workflow-ci-php-dag
spec:
  serviceAccountName: onboarding
  entrypoint: CI-INIT

  arguments: 
    parameters:
      - name: storageclasspvc
        value: "csi-rbd-sc"
      - name: sistema
        value: "wifi"
      - name: unidaddespliegue
        value: "wifi"
      - name: aplicacion
        value: "wifi-portalclave"
      - name: version
        value: "0.0.1"

      - name: repositorio
        value: "git@gitlab.cloudint.afip.gob.ar:wifi/wifi-portalclave.git"
      - name: repositorio-kaniko
        value: "git://gitlab.cloudint.afip.gob.ar/wifi/wifi-portalclave.git"
      - name: destinoHarbor
        value: harbor.prd.afip.gob.ar/{{workflow.parameters.sistema}}-snapshot/{{workflow.parameters.aplicacion}}:{{workflow.parameters.version}}

      #KANIKO
      - name: harborRobotAccountSecret
        value: "robot-wifi-argo"
      - name: harborRobotAccountSecretSnapshot
        value: "robot-wifi-snapshot-argo"
  templates:
    - name: CI-INIT
      dag:
        tasks:        
        - name: DEPENDENCY-CHECK
          templateRef:
            name: php-dependency-check-wt
            template: dependency-check-template
        
        - name: KANIKO-BUILD
          templateRef:
            name: php-kaniko-build-wt
            template: kaniko-clone-build-template

        - name: SONAR
          templateRef:
            name: php-sonar-scanner-wt
            template: sonar-scanner-template

        - name: TRIVY
          dependencies: [KANIKO-BUILD]
          templateRef:
            name: php-trivy-wt
            template: trivy-remote-scan-client-template